[versions]
activity = "1.12.2"
agp = "8.13.2"
appcompat = "1.7.1"
arrow = "2.2.1.1"
browser = "1.9.0"
coil = "2.7.0"
compose = "1.10.0"
compose-material3 = "1.4.0"
constraintlayout = "2.2.1"
core = "1.17.0"
desugar = "2.1.5"
documentfile = "1.1.0"
exif = "1.4.2"
fragment = "1.8.9"
hilt = "1.3.0"
kotlin = "2.3.0"
kotlinx-collections-immutable = "0.4.0"
kotlinx-coroutines = "1.10.2"
lifecycle = "2.10.0"
lint-api = "31.13.2"
localbroadcastmanager = "1.1.0"
material = "1.12.0"
moshi = "1.15.2"
navigation = "2.9.6"
nexus-publish = "2.0.0"
paging = "3.3.6"
preference = "1.2.1"
recyclerview = "1.4.0"
retrofit = "3.0.0"
swiperefresh = "1.2.0"
versions = "0.53.0"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
browser = { module = "androidx.browser:browser", version.ref = "browser" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-runtime-annotation = { module = "androidx.compose.runtime:runtime-annotation", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
core = { module = "androidx.core:core-ktx", version.ref = "core" }
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exif" }
fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lint-api" }
localbroadcastmanager = { module = "androidx.localbroadcastmanager:localbroadcastmanager", version.ref = "localbroadcastmanager" }
material = { module = "com.google.android.material:material", version.ref = "material" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-runtime = { module = "androidx.navigation:navigation-runtime", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
paging-runtime = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }
preference = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefresh" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
lint = { id = "com.android.lint" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }

[bundles]
lifecycle = [
    "lifecycle-common-java8",
    "lifecycle-process",
    "lifecycle-runtime",
    "lifecycle-viewmodel",
    "lifecycle-viewmodel-savedstate"
]
navigation = [
    "navigation-fragment",
    "navigation-ui"
]
moshi = [
    "moshi",
    "moshi-adapters"
]
